platform :ios, '7.0'
pod 'AFNetworking', '~> 2.0'
pod 'Masonry'
pod 'AFMInfoBanner'
pod 'JSONKit-NoWarning', '~> 1.2'
pod 'pop', '~> 1.0.7'
pod 'DGActivityIndicatorView'
pod 'TBIconTransitionKit', '~> 1.0.1'
pod 'SQLCipher', '~> 3.1.0'
pod 'KVOController'
pod 'THPinViewController'
pod 'MJRefresh'
pod 'XLForm', '~> 3.0.2'
pod 'ReactiveCocoa', '~> 2.5'